### ISSUE TITLE
能否支持.env文件以便部署在render？

### ISSUE THREAD

**Issue by nobodysclown** [duolabmeng6/pro-api#1]

**Comment by duolabmeng6** [comment]
可以直接使用远程下载配置
```
services:
  pro-api:
    container_name: pro-api
    image: duolabmeng/pro-api:latest
    environment:
      - config_url=http://file_url/api.yaml
      - secret_key=123456789
    ports:
      - 8001:8000

```
config_url 就可以了 environment 就是环境变量啊配置了就自动远程下载配置
