### ISSUE TITLE
请问如何支持负载均衡？怎么配置

### ISSUE THREAD

**Issue by suneliw** [duolabmeng6/pro-api#3]

**Comment by duolabmeng6** [comment]
今天在写 在思考要不要做到自动停用渠道 还是简单轮训

**Comment by suneliw** [comment]
另外，后台记录的时间不对,docker-compose.yml那里加个时区吧:
environment:
      - TZ=Asia/Shanghai

**Comment by duolabmeng6** [comment]
# 负载均衡

对相同模型名称的模型进行负载均衡

默认权重为1 

```
  - provider: gemini
    name: Gemini1
    base_url: https://generativelanguage.googleapis.com/v1beta
    api_key: 请填写
    model:
      - gemini-1.5-pro
      - gemini-1.5-flash
      - gemini-1.5-flash : gemini-flash
    balance: # 负载均衡
      - gemini-1.5-pro: 1 #表示这个名称下的模型权重是1
      - gemini-1.5-flash: 1 #表示这个名称下的模型权重是2
      - gemini-flash: 1 #表示这个名称下的模型权重是2

  - provider: gemini
    name: Gemini2
    base_url: https://generativelanguage.googleapis.com/v1beta
    api_key: 请填写
    model:
      - gemini-1.5-pro
      - gemini-1.5-flash
      - gemini-1.5-flash : gemini-flash
    balance: # 负载均衡
      - gemini-1.5-pro: 2 #表示这个名称下的模型权重是1
      - gemini-1.5-flash: 2 #表示这个名称下的模型权重是2
      - gemini-flash: 3 #表示这个名称下的模型权重是2
```
以上配置讲解:

比如:

当前权重信息

* Gemini1 的 gemini-1.5-flash 权重1
* Gemini2 的 gemini-1.5-flash 权重2

请求 gemini-1.5-flash 的时候

- 第1次 Gemini1 的 gemini-1.5-flash
- 第2次 Gemini2 的 gemini-1.5-flash
- 第3次 Gemini2 的 gemini-1.5-flash
- 第4次 Gemini1 的 gemini-1.5-flash
- 第5次 Gemini2 的 gemini-1.5-flash

时区的设置了应该可以了~谢谢
