### ISSUE TITLE
多个api_key会报错500

### ISSUE THREAD

**Issue by xmengnet** [duolabmeng6/pro-api#6]
我配置了两个api_key，一个允许all,另一个限制个别模型：
```
tokens:
  - api_key: sk-dxxxx7e63c9e076
    model:
      - all # all 代表全部都可以
  - api_key: sk-05dexxxx1e3
    model:
      - qwen*
      - deepseek-ai*
      - glm*
      - yi*
      - gemma*
      - internlm*
      - meta-llama*
      - mistral*
```
第一个all的正常请求，第二个就会报错：
```
curl -X POST http://127.0.0.1:3030/v1/chat/completions \  
-H "Content-Type: application/json" \
-H "Authorization: Bearer ${API}" \
-d '{"model": "qwen2-72b","messages": [{"role": "user", "content": "Hello"}],"stream": false}'
{"code":500,"message":"成功","detail":"成功","error":{"message":"The server had an error while processing your request.","type":"server_error","param":null,"code":null}}#  
```
all的就正常：
```
curl -X POST http://127.0.0.1:3030/v1/chat/completions \  
-H "Content-Type: application/json" \
-H "Authorization: Bearer ${API}" \  
-d '{"model": "qwen2-72b","messages": [{"role": "user", "content": "Hello"}],"stream": false}'
{"id":"chatcmpl-01937c28709120a12f175cd8dcd2009a","object":"chat.completion","created":1732954846,"model":"Qwen/Qwen2-72B-Instruct","choices":[{"index":0,"message":{"role":"assistant","content":"Hello! How can I assist you today? Let me know if you have any questions or need help with anything. I'm here to help!","tool_calls":null},"finish_reason":"stop"}],"usage":{"prompt_tokens":20,"completion_tokens":29,"total_tokens":49}}
```
帮忙看看是什么原因
